# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Validadores_de_Calidad_Base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Validador(object):
    def setupUi(self, Validador):
        Validador.setObjectName("Validador")
        Validador.resize(400, 376)
        self.verticalLayout = QtWidgets.QVBoxLayout(Validador)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree = QtWidgets.QTreeWidget(Validador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tree.sizePolicy().hasHeightForWidth())
        self.tree.setSizePolicy(sizePolicy)
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)
        self.btnValidar = QtWidgets.QPushButton(Validador)
        self.btnValidar.setObjectName("btnValidar")
        self.verticalLayout.addWidget(self.btnValidar)
        self.btnAyuda = QtWidgets.QPushButton(Validador)
        self.btnAyuda.setObjectName("btnAyuda")
        self.verticalLayout.addWidget(self.btnAyuda)
        self.btnreporte = QtWidgets.QPushButton(Validador)
        self.btnreporte.setObjectName("btnreporte")
        self.verticalLayout.addWidget(self.btnreporte)
        self.btnerrores = QtWidgets.QPushButton(Validador)
        self.btnerrores.setObjectName("btnerrores")
        self.verticalLayout.addWidget(self.btnerrores)

        self.retranslateUi(Validador)
        QtCore.QMetaObject.connectSlotsByName(Validador)

    def retranslateUi(self, Validador):
        _translate = QtCore.QCoreApplication.translate
        Validador.setWindowTitle(_translate("Validador", "Validadores de Calidad"))
        self.tree.headerItem().setText(0, _translate("Validador", "Regla de Calidad"))
        self.tree.headerItem().setText(1, _translate("Validador", "Estado"))
        self.btnValidar.setText(_translate("Validador", "Validar"))
        self.btnAyuda.setText(_translate("Validador", "Ayuda"))
        self.btnreporte.setText(_translate("Validador", "Abrir Reporte"))
        self.btnerrores.setText(_translate("Validador", "Ver resultado"))
