# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAyuda.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.textoManual = QtWidgets.QTextBrowser(Dialog)
        self.textoManual.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.textoManual.setObjectName("textoManual")
        self.btnCerrar = QtWidgets.QPushButton(Dialog)
        self.btnCerrar.setGeometry(QtCore.QRect(290, 270, 93, 28))
        self.btnCerrar.setObjectName("btnCerrar")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCerrar.setText(_translate("Dialog", "Cerrar"))
