# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaErrores.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.busquedaLayout = QtWidgets.QHBoxLayout()
        self.busquedaLayout.setObjectName("busquedaLayout")
        self.labelBusqueda = QtWidgets.QLabel(Dialog)
        self.labelBusqueda.setObjectName("labelBusqueda")
        self.busquedaLayout.addWidget(self.labelBusqueda)
        self.lineaBusqueda = QtWidgets.QLineEdit(Dialog)
        self.lineaBusqueda.setObjectName("lineaBusqueda")
        self.busquedaLayout.addWidget(self.lineaBusqueda)
        self.btnLimpiarBusqueda = QtWidgets.QPushButton(Dialog)
        self.btnLimpiarBusqueda.setAutoDefault(False)
        self.btnLimpiarBusqueda.setObjectName("btnLimpiarBusqueda")
        self.busquedaLayout.addWidget(self.btnLimpiarBusqueda)
        self.verticalLayout.addLayout(self.busquedaLayout)
        self.tablaResultados = QtWidgets.QTableWidget(Dialog)
        self.tablaResultados.setObjectName("tablaResultados")
        self.tablaResultados.setColumnCount(5)
        self.tablaResultados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaResultados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaResultados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaResultados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaResultados.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaResultados.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tablaResultados)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnayuda = QtWidgets.QPushButton(Dialog)
        self.btnayuda.setAutoDefault(False)
        self.btnayuda.setObjectName("btnayuda")
        self.horizontalLayout.addWidget(self.btnayuda)
        self.btnExportar = QtWidgets.QPushButton(Dialog)
        self.btnExportar.setAutoDefault(False)
        self.btnExportar.setObjectName("btnExportar")
        self.horizontalLayout.addWidget(self.btnExportar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btncerrar = QtWidgets.QPushButton(Dialog)
        self.btncerrar.setAutoDefault(False)
        self.btncerrar.setObjectName("btncerrar")
        self.horizontalLayout.addWidget(self.btncerrar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Errores de Validación"))
        self.labelBusqueda.setText(_translate("Dialog", "Buscar:"))
        self.btnLimpiarBusqueda.setText(_translate("Dialog", "Limpiar"))
        item = self.tablaResultados.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Código"))
        item = self.tablaResultados.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "AID"))
        item = self.tablaResultados.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Capa"))
        item = self.tablaResultados.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Regla"))
        item = self.tablaResultados.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Descripción"))
        self.btnayuda.setText(_translate("Dialog", "Ayuda"))
        self.btnExportar.setText(_translate("Dialog", "Exportar"))
        self.btncerrar.setText(_translate("Dialog", "Cerrar"))
